AWSTemplateFormatVersion: "2010-09-09"
Resources:

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: poc-apigateway-authorizer
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: poc-apigateway-authorizer
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      UserPoolId: !Ref CognitoUserPool

  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: poc-apigateway-authorizer
      ProtocolType: HTTP

  HttpApiAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref HttpApi
      AuthorizerType: JWT
      IdentitySource:
        - "$request.header.Authorization"
      JwtConfiguration:
        Audience:
          - !Ref CognitoUserPoolClient
        Issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
      Name: JwtAuthorizer

  HttpApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationMethod: GET
      IntegrationType: HTTP_PROXY
      IntegrationUri: https://github.com/raphaelbh
      PayloadFormatVersion: 1.0

  HttpApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      AuthorizationType: JWT
      AuthorizerId: !Ref HttpApiAuthorizer
      RouteKey: GET /
      Target: !Sub "integrations/${HttpApiIntegration}"

  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      AutoDeploy: true
      StageName: $default

Outputs:

  HttpApiUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"

  CognitoUserPool:
    Value: !Ref CognitoUserPool

  CognitoUserPoolClient:
    Value: !Ref CognitoUserPoolClient